#Le copié collé est votre ami pour créer de l'art ascii!
print("                     jet'aime                               jet'aime                          ")
print("                   jet'aimejet'                           aimejet'aime                        ")
print("                jet'aimejet'aimeje                     jet'aimejet'aimeje                     ")
print("            jet'aimejet'aimejet'aimeje             jet'aimejet'aimejet'aimeje                 ")
print("         jet'aimejet'aimejet'aimejet'aimejet'a   imejet'aimejet'aimejet'aimejet'ai            ")
print("       jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aim        ")
print("     jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet      ")
print("   jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimeet'aimejet'aimejet'aimejet'aime    ")
print("  jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimej   ")
print(" jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet  ")
print("jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print(" jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("  jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimeje")
print("   jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aime")
print("    jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("     jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("      jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimeje")
print("       jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aime")
print("        jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("         jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("          jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimeje")
print("           jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aime")
print("            jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("             jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("               jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aime")
print("                 jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("                   jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'aime")
print("                     jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimejet'ai")
print("                       jet'aimejet'aimejet'aimejet'aimejet'aimejet'aimeje")
print("                          jet'aimejet'aimejet'aimejet'aimejet'aimejet'")
print("                             jet'aimejet'aimejet'aimejet'aimejet'ai")
print("                                jet'aimejet'aimejet'aimejet'aime")
print("                                    jet'aimejet'aimejet'aime")
print("                                        jet'aimejet'aime")
print("                                            jet'aime")
print("                                              jet")

